package:
  name: nexusformat
  version: "1.0.6"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v1.0.6

build:
  entry_points:
    - nexusformat = nexusformat.scripts.nexusformat:main
    - nxstack = nexusformat.scripts.nxstack:main
    - nxduplicate = nexusformat.scripts.nxduplicate:main
    - nxconsolidate = nexusformat.scripts.nxconsolidate:main
    - nxdir = nexusformat.scripts.nxdir:main
number: 0

requirements:
  build:
    - python >=3.8
    - setuptools
    - setuptools_scm

  run:
    - python >=3.8
    - numpy
    - scipy
    - h5py
    - hdf5plugin

test:
  commands:
    - nexusformat --version
    - pytest

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
